apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: shuviru219/myapache1:v2
    ports:
    - name: nodejs-port
      containerPort: 80
